name: Tự động cập nhật link M3U

on:
  schedule:
    - cron: '0 5,11 * * *' # Tự động chạy vào 12h trưa và 18h tối giờ VN
  workflow_dispatch: # Cho phép chạy thủ công

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cài đặt Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện
        run: pip install requests beautifulsoup4

      - name: Chạy Script
        run: python scraper.py

      - name: Lưu file m3u lên GitHub
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add bongda.m3u
          git commit -m "Auto update IPTV links" || exit 0
          git push
